version: '3.9'

services:
  pm2_api:
    build:
      context: .
      dockerfile: Dockerfile_PM2
    volumes:
      - ./dist:/usr/dist
    ports:
      - '5000:5000'
    expose:
      - 5000
    environment:
      PORT: 5000

  nginx_pm2:
    image: nginx:1.23.3-alpine
    ports:
      - '8080:8080'
    environment:
      APP_NAME: pm2_ngnix_api
      PM2_API: pm2_api:5000
      NGINX_PORT: 8080
    volumes:
      - ./docker/nginx/templates/pm2:/etc/nginx/templates
    depends_on:
      - pm2_api

  node_api_1:
    build:
      context: .
      dockerfile: Dockerfile_NODEJS
    volumes:
      - ./dist:/usr/dist
    ports:
      - '5001:5001'
    environment:
      PORT: 5001
    restart: always
    # enable the line for reloads
    # command: nodemon dist/index.js

  node_api_2:
    build:
      context: .
      dockerfile: Dockerfile_NODEJS
    volumes:
      - ./dist:/usr/dist
    ports:
      - '5002:5002'
    environment:
      PORT: 5002
    restart: always
    # enable the line for reloads
    # command: nodemon dist/index.js

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - '8081:8081'
    environment:
      APP_NAME: ngnix_api
      INSTANCE_1: node_api_1:5001
      INSTANCE_2: node_api_2:5002
      NGINX_PORT: 8081
    volumes:
      - ./docker/nginx/templates/node:/etc/nginx/templates
    depends_on:
      - node_api_1
      - node_api_2

volumes:
  ngnix:
    driver: local
